### ISSUE TITLE
Migrate Meican to OSCARS v0.6

### ISSUE THREAD

**Issue by faustovetter** [ufrgs-hyman/meican#1]
One of the OSCARS developers had a chance to briefly look over it and
mentioned a few possible issues:

- the wrappers for GetTopology and RefreshPath in MEICAN are no longer
supported in OSCARS v0.6

- in OSCARS v0.6 we added an optional message properties element to all
the messages which contains a global transaction id and a name for the
message originator. But it can be omitted unless you want to use it.

- in OSCARS v0.5 we used the axis2/rampart tooling for the web services
but in OSCARS v0.6 we use cxf.  Since you are using a php client there
may be some tweaks needed to get the messages on the wire compatible.  
Sometimes the way the namespaces are included in the messages can be
different.  Hopefully by now the WS tools are mature enough that this is
not a big deal

**Comment by mqgmaster** [comment]
OSCARS support has been removed since version 2.
