### ISSUE TITLE
Funcionalidade de Log

### ISSUE THREAD

**Issue by faustovetter** [ufrgs-hyman/meican#13]
Caros,

Observei que fica muito difícil saber qual a razão para uma reserva falhar. Seria importante ter uma funcionalidade de Logging e que isso fosse mostrado na interface para o usuário final.

Sds,
Fausto

**Comment by mqgmaster** [comment]
Issue será abordada na tarefa #618 do redmine.

**Comment by mqgmaster** [comment]
Issue fechada a partir da versão 3
