### ISSUE TITLE
"Network Engineer" role

### ISSUE THREAD

**Issue by faustovetter** [ufrgs-hyman/meican#2]
* It would be great if there was a "Network Engineer" role that could
view the complete path (explicit route object) of the circuit through
the next work.  It would also be really nice if an engineer could
specify the hop-by-hop path in a specific network (for example in
his/her domain) if the detailed topology information was available.

**Comment by mqgmaster** [comment]
Currently MEICAN shows the complete path received from the configured NSI provider.
