### ISSUE TITLE
NSI Authorization using OAuth

### ISSUE THREAD

**Issue by mqgmaster** [ufrgs-hyman/meican#38]
SURFnet implements authentication using Oauth2, but meican currently doesn't provide a way to input the authentication token. 

The Authentication and Authorization in NSI procotol is documented in the following file: [draft-gwdi-trompert-nsi_aa-public-comment-v7.pdf](https://wiki.rnp.br/download/attachments/92224105/draft-gwdi-trompert-nsi_aa-public-comment-v7.pdf?version=1&modificationDate=1493207376000&api=v2) Section 7.2.1

**Comment by mqgmaster** [comment]
MEICAN implementation follows the NSI client from surfnet BandwidthOnDemand.

https://github.com/BandwidthOnDemand/bandwidth-on-demand/blob/master/src/test/resources/web/services/nsiv2/reserve_with_auth_header.xml

Tests with real provider pending.

**Comment by mqgmaster** [comment]
OpenNSA support is incompatible with current NSI AA implementation.

**Comment by htj** [comment]
What exactly is missing from OpenNSA?

It's been a while since I looked at the code, but AFAICT the SOAP stack parses the header and security attributes. They aren't really used anywhere, so there might be bugs with some things in it, since the code paths are not well tested.

**Comment by mqgmaster** [comment]
@htj, I just commited some changes in MEICAN for the support of OpenNSA providers.

Can you test in your environment?

**Comment by htj** [comment]
Hi

I'm not sure what you'd like me to test. I don't have a i MEICAN installation (but I like the concept).

If you have some specific functionality / integration tests you'd like to have seen tested, I will definitely consider adding it to the automated test cases in OpenNSA.

**Comment by mqgmaster** [comment]
@htj, 

Perfect, I hope to have some automated tests soon.
