### ISSUE TITLE
Melhoria na interface para notificações ao usuário da aplicação

### ISSUE THREAD

**Issue by asmoura** [ufrgs-hyman/meican#61]
Na interface gráfica, seria interessante ter uma forma de notificação mais "forte" e obrigatória que a opcional, que o usuário só visualiza após clicar em um ícone. Por exemplo, avisos de manutenções ou de problemas na infraestutura do serviço podem ser motivos "fortes" suficiente para justificar um amplo aviso aos usuários com acesso à interface gráfica da plataforma. Um exemplo de notificação que não dá pra escapar é esse do screenshot, onde a mensagem é fornecida em uma tarja com cor de fundo de destaque (no caso, amarelo), no topo da interface:  

![image](https://user-images.githubusercontent.com/13787091/51625142-9542a500-1f23-11e9-8649-c2b755a78576.png)

Essa seria apenas uma melhoria com baixa prioridade para implementação no futuro. 
Não é algo urgente.

**Comment by leonardolauryel** [comment]
The requested improvement related to bell notification was solved.
Previously, when there wasn't notification, the number 0 was shown.
Now, when there is no notification, no number is shown (as shown in the print below).

![image](https://user-images.githubusercontent.com/39543591/55726540-6dbd8d80-59e6-11e9-8227-523603336bcd.png)

Solution commit:
https://github.com/ufrgs-hyman/meican/commit/c791e71c10f477fa7ef2d929f711902db00471df
